version: "3.7"

services:
  postgres:
    image: postgres:15.2  # Chỉ định phiên bản cụ thể
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: mystore
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:6.18  # Chỉ định phiên bản cụ thể
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@admin.com
      PGADMIN_DEFAULT_PASSWORD: aaa
    ports:
      - "5050:80"
    networks:
      - app_network

  webapi:
    build:
      context: .
      dockerfile: Dockerfile  # Sử dụng Dockerfile trong thư mục hiện tại
    container_name: webapi_container
    restart: always
    ports:
      - "8081:8080"
    networks:
      - app_network

  nginx:
    image: nginx:1.23.4  # Sử dụng nginx với version cụ thể
    container_name: nginx_container
    restart: always
    depends_on:
      - webapi
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Đảm bảo file nginx.conf tồn tại
    ports:
      - "80:80"
    networks:
      - app_network

volumes:
  postgres-data:

networks:
  app_network:
    driver: bridge
