# Sử dụng image NGINX chính thức làm base image
FROM nginx:alpine

# Xoá cấu hình mặc định của NGINX
RUN rm /etc/nginx/conf.d/default.conf

# Sao chép cấu hình NGINX tùy chỉnh vào container
COPY nginx.conf /etc/nginx/nginx.conf

# Sao chép các file tĩnh của Web API hoặc ứng dụng vào thư mục của NGINX
COPY ./public /usr/share/nginx/html

# Mở cổng 80 để phục vụ HTTP
EXPOSE 80

# Khởi chạy NGINX khi container được chạy
CMD ["nginx", "-g", "daemon off;"]
