# Sử dụng image nginx-extras chính thức làm base image
FROM byjg/nginx-extras

# Cấu hình NGINX (sao chép file nginx.conf tùy chỉnh)
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

# Sao chép các file tĩnh vào thư mục phục vụ của NGINX
COPY ./static /static

# Mở cổng 80 cho ứng dụng NGINX
EXPOSE 80

# Khởi chạy NGINX khi container được chạy
CMD ["nginx", "-g", "daemon off;"]
